### ISSUE TITLE
Broucken command `java -jar Zeus-5.jar maven -b`

### ISSUE THREAD

**Issue by seralekseenko** [Kovalevskyi-Academy/Zeus#57]
Условия:
- Зевс лежит в корне проекта
- действия выполняются в контейнере

**Предположение:** в контейнере не натроены переменные среды окружения, что и привело к ошибке.

Результат `java -jar Zeus-5.jar -d maven -b`:
```java
seralekseenko@be30b85edd67:~/urkaganspracovanij-gmail-com$ java -jar Zeus-5.jar -d maven -b
org.apache.maven.shared.invoker.MavenInvocationException: Error configuring command-line. Reason: Maven executable not found at: /usr/bin/bin/mvn
	at org.apache.maven.shared.invoker.DefaultInvoker.execute(DefaultInvoker.java:105)
	at academy.kovalevskyi.zeus.engine.maven.MavenEngine.execute(MavenEngine.java:36)
	at academy.kovalevskyi.zeus.cli.command.sub.Maven.call(Maven.java:31)
	at academy.kovalevskyi.zeus.cli.command.sub.Maven.call(Maven.java:14)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at academy.kovalevskyi.zeus.TheMighty.main(TheMighty.java:12)
Caused by: org.apache.maven.shared.invoker.CommandLineConfigurationException: Maven executable not found at: /usr/bin/bin/mvn
	at org.apache.maven.shared.invoker.MavenCommandLineBuilder.findMavenExecutable(MavenCommandLineBuilder.java:606)
	at org.apache.maven.shared.invoker.MavenCommandLineBuilder.build(MavenCommandLineBuilder.java:68)
	at org.apache.maven.shared.invoker.DefaultInvoker.execute(DefaultInvoker.java:101)
	... 11 more
```

**Comment by EcstasyAwesome** [comment]
@seralekseenko верное предположение)

попробуй указать расположение мавена вручную
`-d maven -m"maven home dir" -b`

**Comment by seralekseenko** [comment]
Я еще попробую задать эти переменные.
Итого:
- попробовать  `-d maven -m"maven home dir" -b`
- задать вручную в контейнере ENV

**Comment by b0noI** [comment]
In the latest container M2_HOME should be set, is this still broken?

**Comment by b0noI** [comment]
@seralekseenko to double check
